/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AccountCommentsRouteImport } from './routes/account.comments'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAccountRouteImport } from './routes/admin.account'
import { Route as AdminCommentsRouteImport } from './routes/admin.comments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSitesRouteImport } from './routes/admin.sites'
import { Route as AdminThreadsRouteImport } from './routes/admin.threads'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginOtpRouteImport } from './routes/login.otp'
import { Route as AccountCommentsCommentIdRouteImport } from './routes/account.comments.$commentId'
import { Route as AdminCommentsCommentIdRouteImport } from './routes/admin.comments.$commentId'
import { Route as OauthCallbackProviderRouteImport } from './routes/oauth.callback.$provider'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountCommentsRoute = AccountCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSitesRoute = AdminSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThreadsRoute = AdminThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginOtpRoute = LoginOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => LoginRoute,
} as any)
const AccountCommentsCommentIdRoute =
  AccountCommentsCommentIdRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => AccountCommentsRoute,
  } as any)
const AdminCommentsCommentIdRoute = AdminCommentsCommentIdRouteImport.update({
  id: '/$commentId',
  path: '/$commentId',
  getParentRoute: () => AdminCommentsRoute,
} as any)
const OauthCallbackProviderRoute = OauthCallbackProviderRouteImport.update({
  id: '/oauth/callback/$provider',
  path: '/oauth/callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRouteWithChildren
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/comments': typeof AdminCommentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/otp': typeof LoginOtpRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/comments': typeof AdminCommentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/otp': typeof LoginOtpRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/authorize': typeof AuthorizeRoute
  '/login': typeof LoginRouteWithChildren
  '/logout': typeof LogoutRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/comments': typeof AdminCommentsRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sites': typeof AdminSitesRoute
  '/admin/threads': typeof AdminThreadsRoute
  '/admin/users': typeof AdminUsersRoute
  '/login/otp': typeof LoginOtpRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/authorize'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin/'
    | '/login/'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/authorize'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin'
    | '/login'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/authorize'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/unsubscribe'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin/'
    | '/login/'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthorizeRoute: typeof AuthorizeRoute
  LoginRoute: typeof LoginRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  OauthCallbackProviderRoute: typeof OauthCallbackProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/comments': {
      id: '/account/comments'
      path: '/comments'
      fullPath: '/account/comments'
      preLoaderRoute: typeof AccountCommentsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/threads': {
      id: '/admin/threads'
      path: '/threads'
      fullPath: '/admin/threads'
      preLoaderRoute: typeof AdminThreadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpRouteImport
      parentRoute: typeof LoginRoute
    }
    '/account/comments/$commentId': {
      id: '/account/comments/$commentId'
      path: '/$commentId'
      fullPath: '/account/comments/$commentId'
      preLoaderRoute: typeof AccountCommentsCommentIdRouteImport
      parentRoute: typeof AccountCommentsRoute
    }
    '/admin/comments/$commentId': {
      id: '/admin/comments/$commentId'
      path: '/$commentId'
      fullPath: '/admin/comments/$commentId'
      preLoaderRoute: typeof AdminCommentsCommentIdRouteImport
      parentRoute: typeof AdminCommentsRoute
    }
    '/oauth/callback/$provider': {
      id: '/oauth/callback/$provider'
      path: '/oauth/callback/$provider'
      fullPath: '/oauth/callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountCommentsRouteChildren {
  AccountCommentsCommentIdRoute: typeof AccountCommentsCommentIdRoute
}

const AccountCommentsRouteChildren: AccountCommentsRouteChildren = {
  AccountCommentsCommentIdRoute: AccountCommentsCommentIdRoute,
}

const AccountCommentsRouteWithChildren = AccountCommentsRoute._addFileChildren(
  AccountCommentsRouteChildren,
)

interface AccountRouteChildren {
  AccountCommentsRoute: typeof AccountCommentsRouteWithChildren
  AccountProfileRoute: typeof AccountProfileRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountCommentsRoute: AccountCommentsRouteWithChildren,
  AccountProfileRoute: AccountProfileRoute,
  AccountSecurityRoute: AccountSecurityRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminCommentsRouteChildren {
  AdminCommentsCommentIdRoute: typeof AdminCommentsCommentIdRoute
}

const AdminCommentsRouteChildren: AdminCommentsRouteChildren = {
  AdminCommentsCommentIdRoute: AdminCommentsCommentIdRoute,
}

const AdminCommentsRouteWithChildren = AdminCommentsRoute._addFileChildren(
  AdminCommentsRouteChildren,
)

interface AdminRouteChildren {
  AdminAccountRoute: typeof AdminAccountRoute
  AdminCommentsRoute: typeof AdminCommentsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSitesRoute: typeof AdminSitesRoute
  AdminThreadsRoute: typeof AdminThreadsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAccountRoute: AdminAccountRoute,
  AdminCommentsRoute: AdminCommentsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSitesRoute: AdminSitesRoute,
  AdminThreadsRoute: AdminThreadsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LoginRouteChildren {
  LoginOtpRoute: typeof LoginOtpRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginOtpRoute: LoginOtpRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthorizeRoute: AuthorizeRoute,
  LoginRoute: LoginRouteWithChildren,
  LogoutRoute: LogoutRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  OauthCallbackProviderRoute: OauthCallbackProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
