/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthorizeRouteImport } from './routes/authorize'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AccountCommentsRouteImport } from './routes/account.comments'

const IndexLazyRouteImport = createFileRoute('/')()
const AccountLazyRouteImport = createFileRoute('/account')()
const AdminLazyRouteImport = createFileRoute('/admin')()
const LoginLazyRouteImport = createFileRoute('/login')()
const LogoutLazyRouteImport = createFileRoute('/logout')()
const ResetPasswordLazyRouteImport = createFileRoute('/reset-password')()
const SetupLazyRouteImport = createFileRoute('/setup')()
const AccountProfileLazyRouteImport = createFileRoute('/account/profile')()
const AccountSecurityLazyRouteImport = createFileRoute('/account/security')()
const AdminIndexLazyRouteImport = createFileRoute('/admin/')()
const AdminAccountLazyRouteImport = createFileRoute('/admin/account')()
const AdminCommentsLazyRouteImport = createFileRoute('/admin/comments')()
const AdminSettingsLazyRouteImport = createFileRoute('/admin/settings')()
const AdminSitesLazyRouteImport = createFileRoute('/admin/sites')()
const AdminThreadsLazyRouteImport = createFileRoute('/admin/threads')()
const AdminUsersLazyRouteImport = createFileRoute('/admin/users')()
const LoginIndexLazyRouteImport = createFileRoute('/login/')()
const LoginOtpLazyRouteImport = createFileRoute('/login/otp')()
const AccountCommentsCommentIdLazyRouteImport = createFileRoute(
  '/account/comments/$commentId',
)()
const AdminCommentsCommentIdLazyRouteImport = createFileRoute(
  '/admin/comments/$commentId',
)()
const OauthCallbackProviderLazyRouteImport = createFileRoute(
  '/oauth/callback/$provider',
)()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AccountLazyRoute = AccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/account.lazy').then((d) => d.Route))
const AdminLazyRoute = AdminLazyRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/admin.lazy').then((d) => d.Route))
const AuthorizeRoute = AuthorizeRouteImport.update({
  id: '/authorize',
  path: '/authorize',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/authorize.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const LogoutLazyRoute = LogoutLazyRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/logout.lazy').then((d) => d.Route))
const ResetPasswordLazyRoute = ResetPasswordLazyRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/reset-password.lazy').then((d) => d.Route),
)
const SetupLazyRoute = SetupLazyRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/setup.lazy').then((d) => d.Route))
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/unsubscribe.lazy').then((d) => d.Route))
const AccountCommentsRoute = AccountCommentsRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AccountLazyRoute,
} as any).lazy(() =>
  import('./routes/account.comments.lazy').then((d) => d.Route),
)
const AccountProfileLazyRoute = AccountProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountLazyRoute,
} as any).lazy(() =>
  import('./routes/account.profile.lazy').then((d) => d.Route),
)
const AccountSecurityLazyRoute = AccountSecurityLazyRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountLazyRoute,
} as any).lazy(() =>
  import('./routes/account.security.lazy').then((d) => d.Route),
)
const AdminIndexLazyRoute = AdminIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const AdminAccountLazyRoute = AdminAccountLazyRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.account.lazy').then((d) => d.Route))
const AdminCommentsLazyRoute = AdminCommentsLazyRouteImport.update({
  id: '/comments',
  path: '/comments',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.comments.lazy').then((d) => d.Route),
)
const AdminSettingsLazyRoute = AdminSettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() =>
  import('./routes/admin.settings.lazy').then((d) => d.Route),
)
const AdminSitesLazyRoute = AdminSitesLazyRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.sites.lazy').then((d) => d.Route))
const AdminThreadsLazyRoute = AdminThreadsLazyRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.threads.lazy').then((d) => d.Route))
const AdminUsersLazyRoute = AdminUsersLazyRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminLazyRoute,
} as any).lazy(() => import('./routes/admin.users.lazy').then((d) => d.Route))
const LoginIndexLazyRoute = LoginIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginLazyRoute,
} as any).lazy(() => import('./routes/login.index.lazy').then((d) => d.Route))
const LoginOtpLazyRoute = LoginOtpLazyRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => LoginLazyRoute,
} as any).lazy(() => import('./routes/login.otp.lazy').then((d) => d.Route))
const AccountCommentsCommentIdLazyRoute =
  AccountCommentsCommentIdLazyRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => AccountCommentsRoute,
  } as any).lazy(() =>
    import('./routes/account.comments.$commentId.lazy').then((d) => d.Route),
  )
const AdminCommentsCommentIdLazyRoute =
  AdminCommentsCommentIdLazyRouteImport.update({
    id: '/$commentId',
    path: '/$commentId',
    getParentRoute: () => AdminCommentsLazyRoute,
  } as any).lazy(() =>
    import('./routes/admin.comments.$commentId.lazy').then((d) => d.Route),
  )
const OauthCallbackProviderLazyRoute =
  OauthCallbackProviderLazyRouteImport.update({
    id: '/oauth/callback/$provider',
    path: '/oauth/callback/$provider',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/oauth.callback.$provider.lazy').then((d) => d.Route),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AccountLazyRouteWithChildren
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRouteWithChildren
  '/logout': typeof LogoutLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/setup': typeof SetupLazyRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileLazyRoute
  '/account/security': typeof AccountSecurityLazyRoute
  '/admin/account': typeof AdminAccountLazyRoute
  '/admin/comments': typeof AdminCommentsLazyRouteWithChildren
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/sites': typeof AdminSitesLazyRoute
  '/admin/threads': typeof AdminThreadsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/login/otp': typeof LoginOtpLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdLazyRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdLazyRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AccountLazyRouteWithChildren
  '/logout': typeof LogoutLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/setup': typeof SetupLazyRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileLazyRoute
  '/account/security': typeof AccountSecurityLazyRoute
  '/admin/account': typeof AdminAccountLazyRoute
  '/admin/comments': typeof AdminCommentsLazyRouteWithChildren
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/sites': typeof AdminSitesLazyRoute
  '/admin/threads': typeof AdminThreadsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/login/otp': typeof LoginOtpLazyRoute
  '/admin': typeof AdminIndexLazyRoute
  '/login': typeof LoginIndexLazyRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdLazyRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdLazyRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/authorize': typeof AuthorizeRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/account': typeof AccountLazyRouteWithChildren
  '/admin': typeof AdminLazyRouteWithChildren
  '/login': typeof LoginLazyRouteWithChildren
  '/logout': typeof LogoutLazyRoute
  '/reset-password': typeof ResetPasswordLazyRoute
  '/setup': typeof SetupLazyRoute
  '/account/comments': typeof AccountCommentsRouteWithChildren
  '/account/profile': typeof AccountProfileLazyRoute
  '/account/security': typeof AccountSecurityLazyRoute
  '/admin/account': typeof AdminAccountLazyRoute
  '/admin/comments': typeof AdminCommentsLazyRouteWithChildren
  '/admin/settings': typeof AdminSettingsLazyRoute
  '/admin/sites': typeof AdminSitesLazyRoute
  '/admin/threads': typeof AdminThreadsLazyRoute
  '/admin/users': typeof AdminUsersLazyRoute
  '/login/otp': typeof LoginOtpLazyRoute
  '/admin/': typeof AdminIndexLazyRoute
  '/login/': typeof LoginIndexLazyRoute
  '/account/comments/$commentId': typeof AccountCommentsCommentIdLazyRoute
  '/admin/comments/$commentId': typeof AdminCommentsCommentIdLazyRoute
  '/oauth/callback/$provider': typeof OauthCallbackProviderLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authorize'
    | '/unsubscribe'
    | '/account'
    | '/admin'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin/'
    | '/login/'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authorize'
    | '/unsubscribe'
    | '/account'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin'
    | '/login'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  id:
    | '__root__'
    | '/'
    | '/authorize'
    | '/unsubscribe'
    | '/account'
    | '/admin'
    | '/login'
    | '/logout'
    | '/reset-password'
    | '/setup'
    | '/account/comments'
    | '/account/profile'
    | '/account/security'
    | '/admin/account'
    | '/admin/comments'
    | '/admin/settings'
    | '/admin/sites'
    | '/admin/threads'
    | '/admin/users'
    | '/login/otp'
    | '/admin/'
    | '/login/'
    | '/account/comments/$commentId'
    | '/admin/comments/$commentId'
    | '/oauth/callback/$provider'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthorizeRoute: typeof AuthorizeRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  AccountLazyRoute: typeof AccountLazyRouteWithChildren
  AdminLazyRoute: typeof AdminLazyRouteWithChildren
  LoginLazyRoute: typeof LoginLazyRouteWithChildren
  LogoutLazyRoute: typeof LogoutLazyRoute
  ResetPasswordLazyRoute: typeof ResetPasswordLazyRoute
  SetupLazyRoute: typeof SetupLazyRoute
  OauthCallbackProviderLazyRoute: typeof OauthCallbackProviderLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authorize': {
      id: '/authorize'
      path: '/authorize'
      fullPath: '/authorize'
      preLoaderRoute: typeof AuthorizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/comments': {
      id: '/account/comments'
      path: '/comments'
      fullPath: '/account/comments'
      preLoaderRoute: typeof AccountCommentsRouteImport
      parentRoute: typeof AccountLazyRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileLazyRouteImport
      parentRoute: typeof AccountLazyRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityLazyRouteImport
      parentRoute: typeof AccountLazyRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/comments': {
      id: '/admin/comments'
      path: '/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/sites': {
      id: '/admin/sites'
      path: '/sites'
      fullPath: '/admin/sites'
      preLoaderRoute: typeof AdminSitesLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/threads': {
      id: '/admin/threads'
      path: '/threads'
      fullPath: '/admin/threads'
      preLoaderRoute: typeof AdminThreadsLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersLazyRouteImport
      parentRoute: typeof AdminLazyRoute
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexLazyRouteImport
      parentRoute: typeof LoginLazyRoute
    }
    '/login/otp': {
      id: '/login/otp'
      path: '/otp'
      fullPath: '/login/otp'
      preLoaderRoute: typeof LoginOtpLazyRouteImport
      parentRoute: typeof LoginLazyRoute
    }
    '/account/comments/$commentId': {
      id: '/account/comments/$commentId'
      path: '/$commentId'
      fullPath: '/account/comments/$commentId'
      preLoaderRoute: typeof AccountCommentsCommentIdLazyRouteImport
      parentRoute: typeof AccountCommentsRoute
    }
    '/admin/comments/$commentId': {
      id: '/admin/comments/$commentId'
      path: '/$commentId'
      fullPath: '/admin/comments/$commentId'
      preLoaderRoute: typeof AdminCommentsCommentIdLazyRouteImport
      parentRoute: typeof AdminCommentsLazyRoute
    }
    '/oauth/callback/$provider': {
      id: '/oauth/callback/$provider'
      path: '/oauth/callback/$provider'
      fullPath: '/oauth/callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountCommentsRouteChildren {
  AccountCommentsCommentIdLazyRoute: typeof AccountCommentsCommentIdLazyRoute
}

const AccountCommentsRouteChildren: AccountCommentsRouteChildren = {
  AccountCommentsCommentIdLazyRoute: AccountCommentsCommentIdLazyRoute,
}

const AccountCommentsRouteWithChildren = AccountCommentsRoute._addFileChildren(
  AccountCommentsRouteChildren,
)

interface AccountLazyRouteChildren {
  AccountCommentsRoute: typeof AccountCommentsRouteWithChildren
  AccountProfileLazyRoute: typeof AccountProfileLazyRoute
  AccountSecurityLazyRoute: typeof AccountSecurityLazyRoute
}

const AccountLazyRouteChildren: AccountLazyRouteChildren = {
  AccountCommentsRoute: AccountCommentsRouteWithChildren,
  AccountProfileLazyRoute: AccountProfileLazyRoute,
  AccountSecurityLazyRoute: AccountSecurityLazyRoute,
}

const AccountLazyRouteWithChildren = AccountLazyRoute._addFileChildren(
  AccountLazyRouteChildren,
)

interface AdminCommentsLazyRouteChildren {
  AdminCommentsCommentIdLazyRoute: typeof AdminCommentsCommentIdLazyRoute
}

const AdminCommentsLazyRouteChildren: AdminCommentsLazyRouteChildren = {
  AdminCommentsCommentIdLazyRoute: AdminCommentsCommentIdLazyRoute,
}

const AdminCommentsLazyRouteWithChildren =
  AdminCommentsLazyRoute._addFileChildren(AdminCommentsLazyRouteChildren)

interface AdminLazyRouteChildren {
  AdminAccountLazyRoute: typeof AdminAccountLazyRoute
  AdminCommentsLazyRoute: typeof AdminCommentsLazyRouteWithChildren
  AdminSettingsLazyRoute: typeof AdminSettingsLazyRoute
  AdminSitesLazyRoute: typeof AdminSitesLazyRoute
  AdminThreadsLazyRoute: typeof AdminThreadsLazyRoute
  AdminUsersLazyRoute: typeof AdminUsersLazyRoute
  AdminIndexLazyRoute: typeof AdminIndexLazyRoute
}

const AdminLazyRouteChildren: AdminLazyRouteChildren = {
  AdminAccountLazyRoute: AdminAccountLazyRoute,
  AdminCommentsLazyRoute: AdminCommentsLazyRouteWithChildren,
  AdminSettingsLazyRoute: AdminSettingsLazyRoute,
  AdminSitesLazyRoute: AdminSitesLazyRoute,
  AdminThreadsLazyRoute: AdminThreadsLazyRoute,
  AdminUsersLazyRoute: AdminUsersLazyRoute,
  AdminIndexLazyRoute: AdminIndexLazyRoute,
}

const AdminLazyRouteWithChildren = AdminLazyRoute._addFileChildren(
  AdminLazyRouteChildren,
)

interface LoginLazyRouteChildren {
  LoginOtpLazyRoute: typeof LoginOtpLazyRoute
  LoginIndexLazyRoute: typeof LoginIndexLazyRoute
}

const LoginLazyRouteChildren: LoginLazyRouteChildren = {
  LoginOtpLazyRoute: LoginOtpLazyRoute,
  LoginIndexLazyRoute: LoginIndexLazyRoute,
}

const LoginLazyRouteWithChildren = LoginLazyRoute._addFileChildren(
  LoginLazyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthorizeRoute: AuthorizeRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  AccountLazyRoute: AccountLazyRouteWithChildren,
  AdminLazyRoute: AdminLazyRouteWithChildren,
  LoginLazyRoute: LoginLazyRouteWithChildren,
  LogoutLazyRoute: LogoutLazyRoute,
  ResetPasswordLazyRoute: ResetPasswordLazyRoute,
  SetupLazyRoute: SetupLazyRoute,
  OauthCallbackProviderLazyRoute: OauthCallbackProviderLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
